[user]
name = "Graeme Coupar"
email = "graeme@turbofish.tech"

[snapshot]
#max-new-file-size = "10MiB"

[git]
push-bookmark-prefix = "obmarg/"

[ui]
#diff-editor = "meld-3"
#diff-editor = ["ksdiff", "--merge", "$left", "$right"]
#merge-editor = ["ksdiff", "--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
merge-editor = "vscode"
#diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]
#diff.format = "git"
#pager = ["sh", "-c", "diff-so-fancy | less -RFX"]
#pager = "delta"
diff.tool = ["difft", "--color=always", "$left", "$right"]

[aliases]
l = ['log', '--no-pager', '--reversed']
s = ['status']
forcibly = ["--config-toml=revset-aliases.'immutable_heads()' = 'none()'"]

[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.email().local()'
'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_id(id)' = 'id.shortest(6)'

[revsets]
# Changing this from the default `@ | ancestors(immutable_heads().., 2) | heads(immutable_heads())`
# Default found here: https://github.com/martinvonz/jj/blob/2e64bf83fd9b8abf4c9880482ea4ce19492f3139/lib/src/settings.rs#L213
# This is basically the default but hiding any non-local branches
# Note: at some point might want to update this in line with https://github.com/martinvonz/jj/commit/62f0cb8c3f03ade34e8862ba0cd600603fc4a91a
log = "@::trunk() | ((ancestors(immutable_heads().., 2) | heads(immutable_heads())) ~ (remote_bookmarks() ~ bookmarks()) ~ tags())"

[revset-aliases]
"immutable_heads()" = "trunk() | tags() | (trunk().. & ~mine())"

"common_ancestor(a,b)"="heads(::a & ::b)"
"diverge(a,b)"="common_ancestor(a,b)::(a|b)"

[colors]
"prefix" = "cyan"
"rest" = "bright black"

# Also don't highlight divergent stuff (the red ?? is fine with me)
"divergent prefix" = "bright black"
"divergent rest" = "bright black"

"branches" = "yellow"
"git_refs" = "yellow"
"git_head" = "yellow"

"timestamp" = "blue"
"username" = "green"

"working_copy" = { bold = true }
