alias jjl='jj l'
alias jjs='jj s'

alias jjf='jj git fetch'
alias jjp='jj git push'
alias jjpc='jj git push -c @'
alias jjd='jj describe'
alias jjn='jj new'
alias jjr='jj rebase'
alias jjb='jj bookmark'
